### ISSUE TITLE
Supprimer la balise "Nofollow" sur les pages "Entreprises"

### ISSUE THREAD

**Issue by Jonathan2051** [annuaire-entreprises-data-gouv-fr/seo#13]
- Le problème : la balise "Nofollow" doit être supprimée du bouton "Télécharger le justificatif d'immatriculation"

- Pourquoi ? Cette balise envoie un message négatif à Google quant à la qualité de la page en question

- Localisation : Page "Entreprises" > Onglet "Documents" > Bouton "Télécharger le justificatif d'immatriculation"

- Exemple : https://annuaire-entreprises.data.gouv.fr/documents/451321335

**Comment by rmonnier9** [comment]
<img width="736" alt="image" src="https://github.com/user-attachments/assets/558b95bc-b84b-4114-91c7-30875bf9904c">

**Comment by Jonathan2051** [comment]
C'est bon pour moi ✅
